---
apiVersion: v1
kind: Service
metadata:
  name: kafka-server
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
        - name: init-zookeeper
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              'result=1; until [ ${result} -eq 0 ]; do OK=$(echo ruok | nc -w 1 zookeeper-server.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local 2181); if [ "${OK}" == "imok" ]; then result=0; echo "zookeeper returned imok!"; else echo waiting for zookeeper service..; sleep 1; fi; done; echo "[OK] zookeeper is ready"',
            ]
      containers:
        - name: broker
          image: wurstmeister/kafka
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 35
            timeoutSeconds: 5
          env:
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-server:2181
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-server:9092
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_CREATE_TOPICS
              value: "locations:1:1"
            - name: KAFKA_DELETE_TOPICS_ENABLE
              value: "true"
