---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-app
  name: udaconnect-app
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    service: udaconnect-app
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-app
  name: udaconnect-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-app
  template:
    metadata:
      labels:
        service: udaconnect-app
    spec:
      containers:
        - image: shehabeldeen/udaconnect-app:latest
          name: udaconnect-app
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "64m"
            limits:
              memory: "256Mi"
              cpu: "256m"
          env:
            - name: REACT_APP_CONN_SVC_BASE_URL
              value: "http://localhost:30004/api"

            - name: REACT_APP_PERSON_SVC_BASE_URL
              value: "http://localhost:30003/api"
      restartPolicy: Always
