# TODO: add best practices annotations and comments if needed
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-server
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181

---
apiVersion: v1
kind: ConfigMap
data:
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"
  KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"
metadata:
  name: zookeeper-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-server
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.0.1
          ports:
            - containerPort: 2181
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
          # TODO: use ConfigMap and install it as a file
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-config
                  key: ZOOKEEPER_CLIENT_PORT

            - name: ZOOKEEPER_TICK_TIME
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-config
                  key: ZOOKEEPER_TICK_TIME

            - name: KAFKA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-config
                  key: KAFKA_OPTS
