name: UdaConnect Person Service

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
    paths:
      - modules/udaconnect-persons-service/**
      - .github/workflows/*persons*.yml
  pull_request:
    branches:
      - master
      - "releases/**"

# ensure that only a single job or workflow using the same concurrency group will run at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # cancel previously running builds in a PR on new pushes
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

# set default permissions granted to the GITHUB_TOKEN to read only to follow least privilege principle
permissions: read-all

jobs:
  build:
    # set timeout to 15 mins max to decrease hanging jobs issues, default is 6 Hrs
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/udaconnect-persons-service
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/udaconnect-persons-service
          # generate Docker tags based on the following events/attributes
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
          # generate Docker custom labels
          labels: |
            org.opencontainers.image.title=UdaConnect
            org.opencontainers.image.description=UdaConnect is a service to help attendees make connections that can inform attendees if they have attended the same booths and presentations at an event.
            org.opencontainers.image.vendor=shehabeldeenalalkamy@gmail.com

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./modules/udaconnect-persons-service
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
